name: adaptive_layout_research
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - images/potato.png
      - images/habanero.png
      - images/strawberry.png
      - images/plum.png
      - images/mushroom.png
      - images/avocado.png
